### PR TITLE
[WED-38] Install Bootstrap, Slim, and Slim template generator

### PR DESCRIPTION
**Pull request by jonathanchiu**
This installs 3 gems:
* Bootstrap (front-end framework)
* Slim (template language)
* Slim template (template generator so that view files are auto-generated when controller, etc are generated)

#### Notable changes
Renamed `application.css` to `application.scss` and removed `*= require_tree .` and `*= require_self` as per the gem's docs

### CODE REVIEW

**Comment by ThePletch** [comment]
Since we're using SASS, we should look at setting it as our CSS compressor for all our configs in `config/environments`.

**Comment by ThePletch** [comment]
Beyond adding it as our compressor, LGTM :shipit:

**Comment by jonathanchiu** [comment]
@ThePletch LMK what you think :dancers:

**Comment by ThePletch** [comment]
👌👀👌👀👌👀👌👀👌👀 good code go౦ԁ cOde👌 thats ✔ some good👌👌code right👌👌there👌👌👌 right✔there ✔✔

**Comment by jonathanchiu** [comment]
I can feel the dankness through my laptop screen :ok_hand:

**Pull request merged**
